more matmul operations
slyalin/openvino pull request #50
Opened 2022-11-29 11:09 UTC by eaidova

added tests for `aten::mm`
supported `aten::bmm`, `aten::matmul`, `aten:addmm`

2022-11-29 14:27 UTC, mvafin requested changes

2022-11-29 14:27 UTC, mvafin commented on src/frontends/pytorch/src/op/addmm.cpp
> +    auto mm  = context.mark_node(std::make_shared<opset8::MatMul>(m1, m2));
Please fix codestyle

2022-11-29 14:53 UTC, eaidova commented on src/frontends/pytorch/src/op/addmm.cpp
> +    auto mm  = context.mark_node(std::make_shared<opset8::MatMul>(m1, m2));
fixed

2022-12-06 06:10 UTC, eaidova commented
@mvafin do you have any additional comments?

2022-12-06 12:55 UTC, mvafin approved these changes

2022-12-06 15:57 UTC, merged