Add len operator with layer test
slyalin/openvino pull request #80
Opened 2023-01-03 12:36 UTC by sikorsl1

**Details:**

- `aten::len` operator has been added
- layer test for this operator has been added

**Ticket:**

- 99225

2023-01-05 10:42 UTC, mmikolajcz requested changes

2023-01-05 10:42 UTC, mmikolajcz commented on src/frontends/pytorch/src/op/len.cpp
> +OutputVector translate_len(NodeContext& context) {
From what I've checked in some models, there are some cases where aten::len is called on list and dicts, not only tensors - it would probably need to be handled by transformations.
However, since current implementation still might fix some models, maybe it would be worth to add more complex transformations in separate PR and add tests to ensure that for more complicated datatypes translation would fail in controlled manner?

2023-01-10 11:30 UTC, mvafin commented on src/frontends/pytorch/src/op/len.cpp
> +OutputVector translate_len(NodeContext& context) {
Agree

2023-01-10 11:30 UTC, mvafin approved these changes

2023-01-10 12:48 UTC, merged